### ISSUE TITLE
comments on latest version and some ideas

### ISSUE THREAD

**Issue by alcardini** [zarquon42b/VILDS#6]
[AAA_notes01.pdf](https://github.com/zarquon42b/VILDS/files/8754472/AAA_notes01.pdf)

TEXT WITHOUT FIGURES IS BELOW:

I am playing with VILDS a little bit.
A few comments and suggestions.

This (below) is the output for my fox data, with fake groups.

1) With 2D data, showing the irrelavant ILDs is Okish but I’d remove them as they don’t convey any important information and in 3D (hare example below) they’re confusing.  Either I’d show only the points or would have an option to include a wireframe (if easy to do).

2) I need to explore this further. These data are perfectly symmetric. If ILD 2-12 is supported, ILD 2-8 should be similarly supported. Those R2s are small, and the ratos are even smaller. Thus it makes sense that, randomly, one ILD looks slightly more supported than it’s symmetric ‘partner’ on the other side. Yet, I tried several times and consistently get 2-12 more supported than 2-8: is it because of the random seed number being the same? If so, should that be random as well, so that one does not get this kind of ‘artefact’?

3) For the colours, I’d suggest:
red: strong support for a contraction (ILD in the target is shorter);
orange: same as red by weakly supported;
blue: strong support for an expansion (ILD in the target is longer);
light blue: weakly supported expansion.
They don’t have to be red/orange and blue/light blue but I suggest two colours each with two tones.

4) In the help of ILDSR2 we need to add the default percentile to “R2tol   numeric: upper percentile for ILD R2 in relation to factor”.

5) I wonder whether we might have an option for whether to display ILDs with less than 50% support.

6) In the legend “Bootstrapped (99 rounds) confidence of relevant ILDS” we need to add “in the R2tol percentile”. If the percentile is lower, more ILDS will be supported. This is kind of weird and looks like an inconsistency in the method, but it is inevitable as R2tol is arbitrary. We’ll get criticized but I don’t think it’s a major issue as long as we EMPHASIZE that this is neither a test nor a demonstration of biological relevance. It’s purely a visualization tool to aid detecting major changes in interlandmark regions at a level of ‘resolution’ (the R2tol) which is decided by the user.
I have to think more about this …

7) This (below) is one my Pinocchio examples using the form space:
I can’t remember exactly the data and will have to check (possibly it was all landmarks the same in the two groups except L5 (tip of the nose). If so, it gets the right answer but because of small asymmetries it does not show also 2-5 and 3-5 as main ILDs. If you look at the distribution of R2s (below) you’ll get why: the differences are small but enough to miss them when R2tol=0.8

Now, use R2tol=.5, and here they are:

Stefan, isn’t this suggesting a less arbitrary way to set R2tol? It should be the highest percentile (if any) that marks a gap with lower R2s. Maybe one could plot ILDs R2s in descending order, fit an interpolating function (TPS?) and find the first point where the slope changes sharply (but I am not sure how do define sharp!).

We need more examples where we change just one or a few ILDs between two groups and then we check if we get those right.
I am super-excited and love the package you wrote!

**Comment by zarquon42b** [comment]
Here are my answers:
1. Not a problem. I'll change that behaviour.
2. I realized this as well. No there is no set.seed() statement involved. I used your code for the R2 generation. I also doublechecked with symmetrized data and the result seems to be more or less consistent.
3. I'm on it.
4. Not sure what you are getting at - please elaborate ;)
5. As you could see, users can set their parameters and set it to whatever they consider sensible
6. I already thought of this and would like you to write a longish documentation text which explains that and will go in the "Details" section of the functions help page
7. I have no solution for this as in my testing there often is no such gap or meaningful threshold for R2. The more uniform a shape change is (affecting all landmarks), the less likely you can spot a gap. I am not really worrying because we should encourage users to make their own decisions and clearly state that there is no objective cut-off point.

>  I am super-excited and love the package you wrote!

WE WROTE IT TOGETHER!

**Comment by zarquon42b** [comment]
Remark on 2: I just tried with symmetrized data as well and even when I reshuffle the landmarks, the result of a (slightly but consistently) higher support for the same ILDs as before remains. However, there are still some slight differences in ILDs due to rounding error, but this is somewhere in the region of 1e-9.

**Comment by alcardini** [comment]
4. The help does not say what the R2tol is by default, if one does not set his/her own.
7. I fear you're right but still wonder if there's a way to help users to decide. The Pinocchio example is clearly trivial and has so few points that gaps might be expected.

One of the authors of the IDAV (if that was the name) landmark.exe software was Will HS, a former PhD student of O'Higgins. When the software came out, I told Paul: "Did you see the software Will wrote?".
He answered: "Will can't write his own name ...". I am like Will!

Ciao

Andrea

**Comment by alcardini** [comment]
Something else I just noticed:
"P-value between groups (999 rounds): 0.001001001001001"
Shouldn't that be 0.001?
Cheers

A

**Comment by zarquon42b** [comment]
This is an issue related to Morpho
 Please install it from GitHub where I fixed it.

alcardini ***@***.***> schrieb am Mo., 23. Mai 2022, 16:25:

**Comment by zarquon42b** [comment]
> The help does not say what the R2tol is by default, if one does not set his/her own.

Actually it does, in R the arguments incl. default values are displayed - see here: 
![Selection_127](https://user-images.githubusercontent.com/1515863/169973749-bf0b48aa-a105-4f9d-a562-e59a90f978c2.png)

**Comment by zarquon42b** [comment]
> Remark on 2: I just tried with symmetrized data as well and even when I reshuffle the landmarks, the result of a (slightly but consistently) higher support for the same ILDs as before remains. However, there are still some slight differences in ILDs due to rounding error, but this is somewhere in the region of 1e-9.

Even with symmetrized data, you usually have very slight differences due to rounding errors. Assuming, we are looking for the 2 (or any other value) most important ILDs and during bootsrapping another ILD has a higher R2, the slightly lower R2 value of the symmetrized distances will consistently be outside the "important" range. I checked this thoroughly and it is an artifact from the static threshold.

**Comment by zarquon42b** [comment]
I also added a tentative clustering protocol to automatically find the `R2tol` value from the cluster with the highest R2-values. In cases with no distinct cluster, this might lead to a deterioration of `R2tol`, the value `R2tol` is interpreted as the minimum value `R2tol` is allowed to have.
The new option its default value is `autocluster=FALSE`. For objects with symmetry, it works better on the symmetric data, as this reduces the gradual noise between sides that masks potential cluster borders.

**Comment by zarquon42b** [comment]
Here is what I mean with the autocluster:
```
left <- c(4,6,8)  
right <- c(3,5,7)
pairedLM <- cbind(left,right)
## symmetric proc
proc <- procSym(boneLM,pairedLM = pairedLM)
## standard proc
groups <- name2factor(boneLM,which=3)

ilds.sym <- ILDSR2(proc$Sym,groups,plot=TRUE,wg.rounds=999,mc.cores=2,R2tol=.8,autocluster=T)
## This gives sensible clusters


ilds.nosym <- ILDSR2(proc$rotated,groups,plot=TRUE,wg.rounds=999,mc.cores=2,R2tol=.8,autocluster=T)
## autoclustering fails (as the asymmetric noise muddles the gaps between clusters)

```
